protected/modules/member/models/MemberPricingRate.php
<?php

namespace app\modules\member\models;

use Yii;
use luya\admin\ngrest\base\NgRestModel;
use luya\admin\traits\SoftDeleteTrait;

use app\modules\member\models\Member;
use app\modules\pricing\models\PricingRate;

use yii\behaviors\TimestampBehavior;

/**
 * Member Pricing Rate.
 *
 * File has been created with `crud/create` command.
 *
 * @property integer $jdls_member_detail_id
 * @property integer $jdls_pricing_rate_id
 * @property double $amount
 * @property string $detail
 */
class MemberPricingRate extends NgRestModel
{

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors[] = TimestampBehavior::className();
        return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'jdls_member_princing_rate';
    }

    /**
     * @inheritdoc
     */
    public static function ngRestApiEndpoint()
    {
        return 'api-member-memberpricingrate';
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'jdls_member_detail_id' => Yii::t('app', 'Membre'),
            'jdls_pricing_rate_id' => Yii::t('app', 'Type'),
            'amount' => Yii::t('app', 'Montant/Acompte'),
            'detail' => Yii::t('app', 'Detail'),
            'description' => Yii::t('app', 'Description'),
            'status' => Yii::t('app', 'Statut'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['jdls_member_detail_id', 'jdls_pricing_rate_id', 'is_special', 'status', 'is_tos_accepted', 'has_subscription_fee'], 'integer'],
            [['amount'], 'number'],
            [['detail', 'description'], 'string'],
            [['jdls_member_detail_id'], 'exist', 'skipOnError' => true, 'targetClass' => Member::className(), 'targetAttribute' => ['jdls_member_detail_id' => 'id']],
            [['jdls_pricing_rate_id'], 'exist', 'skipOnError' => true, 'targetClass' => PricingRate::className(), 'targetAttribute' => ['jdls_pricing_rate_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function genericSearchFields()
    {
        return ['detail'];
    }

    /**
     * @inheritdoc
     */
    public function ngRestAttributeTypes()
    {
        return [
            'jdls_member_detail_id' => 'number',
            'jdls_pricing_rate_id' => [
                'selectModel',
                'modelClass' => PricingRate::className(),
                'valueField' => 'id',
                'labelField' => function($model) {
                    $detail = $model->is_special ? 'CT ' : 'Fight ';
                    return  $model->period->pricing->category . ': ' . $detail . ' | ' . $model->period->description . ' | ' . $model->frequency . ' acompte(s)';
                }
            ],
            'amount' => 'decimal',
            'detail' => 'text',
            'description' => 'text',
            'status' => ['toggleStatus', 'initValue' => 0]
        ];
    }

    /**
     * @inheritdoc
     */
    public function ngRestScopes()
    {
        return [
            ['list', ['jdls_pricing_rate_id', 'amount', 'status']],
            [['create', 'update'], ['jdls_member_detail_id', 'jdls_pricing_rate_id', 'amount', 'status']],
            ['delete', true],
        ];
    }

    public function getRate()
    {
        return $this->hasOne(PricingRate::class, ['id' => 'jdls_pricing_rate_id']);
    }

}

protected/modules/member/frontend/controllers/DefaultController.php
<?php

namespace app\modules\member\frontend\controllers;

use app\modules\member\frontend\traits\MemberTrait;
use app\modules\member\models\Address;
use app\modules\member\models\Member;
use app\modules\member\models\MemberPricingRate;
use app\modules\pricing\models\Invoice;
use app\modules\pricing\models\Pricing;
use app\modules\pricing\models\PricingRate;
use app\modules\settings\models\Settings;
use app\modules\training\models\Training;
use Carbon\Carbon;
use Da\User\Event\UserEvent;
use Da\User\Filter\AccessRuleFilter;
use Da\User\Form\SettingsForm;
use Da\User\Model\User;
use Da\User\Traits\ContainerAwareTrait;
use Da\User\Validator\AjaxRequestModelValidator;
use kartik\mpdf\Pdf;
use luya\web\Controller;
use yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\Json;
use yii\helpers\Url;
use yii\web\Response;
use yii\widgets\ActiveForm;

class DefaultController extends Controller
{

    use ContainerAwareTrait, MemberTrait;

    /**
     * @var UserQuery
     */
    protected $member;

    protected $memberType;

    protected $settings;

    public $enableCsrfValidation = false;

    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'logout' => ['POST'],
                    'validate' => ['GET'],
                ],
            ],
            'access' => [
                'class' => AccessControl::class,
                'ruleConfig' => [
                    'class' => AccessRuleFilter::class,
                ],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index', 'training', 'training-weekly', 'subscription', 'invoice', 'settings', 'validate', 'payment', 'view-invoice', 'logout', 'send-notification'],
                        'roles' => ['@'],
                    ],
                    [
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                ],
            ],
        ];
    }

    public function init()
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['/user/login']);
        }

        $this->member = Member::find()
            ->where(['user_id' => Yii::$app->user->id])->one();

        $this->memberType = $this->member->member_type;

        $this->settings = Settings::find()->one();
        $this->member->date_of_birth = Yii::$app->formatter->asDate($this->member->date_of_birth);

        Yii::$app->view->params['days'] = $this->getDays();
    }

    /**
     * Personal information update action
     * @return [type] [description]
     */
    public function actionIndex()
    {
        $address = Address::find()
            ->where(['jdls_member_id' => $this->member->id])->one();

        if (!isset($address)) {
            $address = new Address();
        }

        $this->member->attributes = Yii::$app->request->post('Member');
        $address->attributes = Yii::$app->request->post('Address');

        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($this->member, $address);
        }

        if (Yii::$app->request->post('Member') && $this->member->validate()) {

            $this->member->date_of_birth = Carbon::createFromFormat('d.m.Y', $this->member->date_of_birth)->timestamp;
            $this->member->member_type = $this->memberType;
            $this->member->update();
            Yii::$app->session->setFlash('saved-success', Yii::t('app', 'Enregistrement effectué'));
            return $this->refresh();
        }

        if (Yii::$app->request->post('Address') && $address->validate()) {
            if ($address->isNewRecord) {
                $address->save();
            } else {
                $address->update();
            }

            Yii::$app->session->setFlash('saved-success', Yii::t('app', 'Enregistrement effectué'));
            return $this->refresh();
        }

        return $this->render('index', ['member' => $this->member, 'address' => $address]);

    }

    /**
     * Training POST action
     * @return [type] [description]
     */
    public function actionTraining()
    {

        $trainings = $this->getTraining(false);
        $specialTrainings = $this->getTraining(true);

        $memberPricing = $this->getMemberPricingModel(false);
        $memberSpecialPricing = $this->getMemberPricingModel(true);

        $schedulesArray = $this->initSchedulesArray($trainings);
        $specialSchedulesArray = $this->initSchedulesArray($specialTrainings);

        if (Yii::$app->request->post('MemberSchedule')) {
            if ((bool) Yii::$app->request->get('q')) {
                foreach ($specialTrainings as $trainingKey => $training) {
                    foreach ($training->schedules as $scheduleKey => $schedule) {
                        $postData = Yii::$app->request->post('MemberSchedule')[$trainingKey][$scheduleKey];
                        $currentModel = $specialSchedulesArray[$trainingKey][$scheduleKey];
                        $currentModel->is_subscribed = (int) $postData['is_subscribed'];
                        $currentModel->is_special_training = true;
                        $currentModel->update();
                    }
                }
                Yii::$app->session->setFlash('training-saved-success', Yii::t('app', 'Enregistrement effectué'));
                return $this->refresh();
            } else {
                foreach ($trainings as $trainingKey => $training) {
                    foreach ($training->schedules as $scheduleKey => $schedule) {
                        $postData = Yii::$app->request->post('MemberSchedule')[$trainingKey][$scheduleKey];
                        $currentModel = $schedulesArray[$trainingKey][$scheduleKey];
                        $currentModel->is_subscribed = (int) $postData['is_subscribed'];
                        $currentModel->update();
                    }
                }
                Yii::$app->session->setFlash('training-saved-success', Yii::t('app', 'Enregistrement effectué'));
                return $this->refresh();
            }
        }

        return $this->render('training', [
            'trainings' => $trainings,
            'schedulesArray' => $schedulesArray,
            'specialTrainings' => $specialTrainings,
            'specialSchedulesArray' => $specialSchedulesArray,
            'memberPricing' => $memberPricing,
            'memberSpecialPricing' => $memberSpecialPricing,
            'member' => $this->member,
        ]);

    }

    /**
     * [actionTrainingWeekly description]
     * @param  [type] $day [description]
     * @return [type]      [description]
     */
    public function actionTrainingWeekly($day = null)
    {

        if (isset($day)) {
            $currentDay = $day;
        } else {
            $rawDate = date('m.d.y');
            $currentDay = date('N', strtotime($rawDate));
        }

        $this->view->params['currentDay'] = $currentDay;

        $trainings = $this->getTraining(false);
        $specialTrainings = $this->getTraining(true);

        $schedulesArray = $this->initSchedulesArray($trainings, $currentDay);
        $specialSchedulesArray = $this->initSchedulesArray($specialTrainings, $currentDay);

        $memberPricing = $this->getMemberPricingModel(false);
        $memberSpecialPricing = $this->getMemberPricingModel(true);

        if (Yii::$app->request->post('MemberSchedule')) {
            if ((bool) Yii::$app->request->get('q')) {
                foreach ($specialTrainings as $trainingKey => $training) {
                    foreach ($training->schedules as $scheduleKey => $schedule) {
                        $postData = Yii::$app->request->post('MemberSchedule')[$trainingKey][$scheduleKey];
                        $currentModel = $specialSchedulesArray[$trainingKey][$scheduleKey];
                        $currentModel->is_subscribed = (int) $postData['is_subscribed'];
                        $currentModel->is_special_training = true;
                        $currentModel->update();
                    }
                }
                Yii::$app->session->setFlash('training-saved-success', Yii::t('app', 'Enregistrement effectué'));
                return $this->refresh();
            } else {
                foreach ($trainings as $trainingKey => $training) {
                    foreach ($training->schedules as $scheduleKey => $schedule) {
                        $postData = Yii::$app->request->post('MemberSchedule')[$trainingKey][$scheduleKey];
                        $currentModel = $schedulesArray[$trainingKey][$scheduleKey];
                        $currentModel->is_subscribed = (int) $postData['is_subscribed'];
                        $currentModel->update();
                    }
                }
                Yii::$app->session->setFlash('training-saved-success', Yii::t('app', 'Enregistrement effectué'));
                return $this->refresh();
            }
        }

        return $this->render('training-weekly', [
            'trainings' => $trainings,
            'specialTrainings' => $specialTrainings,
            'schedulesArray' => $schedulesArray,
            'specialSchedulesArray' => $specialSchedulesArray,
            'memberPricing' => $memberPricing,
            'memberSpecialPricing' => $memberSpecialPricing,
            'member' => $this->member,
        ]);
    }

    /**
     * Save member subscription
     * @param  [type] $action [description]
     * @return [type]         [description]
     */
    public function actionSubscription()
    {
        $pricing = Pricing::find()
            ->where(['id' => $this->member->member_type])->one();

        $memberPricingModel = $this->getMemberPricingModel(false);
        $memberSpecialPricingModel = $this->getMemberPricingModel(true);

protected/modules/member/frontend/views/default/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;

use dosamigos\datepicker\DatePicker;

use app\modules\pricing\models\Pricing;

$this->title = Yii::t('app', 'Fight-District | Mon profil');

?>

<div class="row">

    <div class="col-md-10">
        
        <?php if ($flash = Yii::$app->session->getFlash('validation-success')): ?>
            <div class="alert-tmp alert alert-success">
                <p><?= $flash ?></p>
            </div>
        <?php endif; ?>

        <?php if ($flash = Yii::$app->session->getFlash('saved-success')): ?>
            <div class="alert-tmp alert alert-success">
                <p><?= $flash ?></p>
            </div>
        <?php endif; ?>

        <!-- Profile section -->
        <div class="card">
            <div class="header">
                <h4 class="title">Données Personnelles</h4>
            </div>
            <div class="content profile-wrapper">
                <?php $form = ActiveForm::begin(); ?>
                <div class="row">
                    <?= $form->field($member, 'gender', ['options' => [ 'class' => 'col-md-12']])
                        ->radioList([
                            1 => Yii::t('app', 'Mme.'),
                            2 => Yii::t('app', 'M.')
                        ]);
                    ?>
                </div>

                <div class="row">
                    <?= $form->field($member, 'member_type', ['options' => [ 'class' => 'col-md-12']])
                        ->dropDownList(ArrayHelper::map(Pricing::find()->asArray()->all(), 'id', 'category'), ['disabled' => true])
                    ?>
                </div>

                <div class="row">
                    <?= $form->field($member, 'first_name', ['options' => [ 'class' => 'col-md-6']])->textInput() ?>
                    <?= $form->field($member, 'last_name', ['options' => [ 'class' => 'col-md-6']])->textInput() ?>
                </div>

                <div class="row">
                    <?= $form->field($member, 'date_of_birth', ['options' => [ 'class' => 'col-md-12']])
                        ->widget(\yii\widgets\MaskedInput::className(), ['name' => 'date_of_birth',  'clientOptions' => ['alias' =>  'mm.dd.yyyy']]) ?>
                </div>

                <div class="row">
                    <?= $form->field($member, 'phone_fix', ['options' => [ 'class' => 'col-md-6']])->textInput() ?>
                    <?= $form->field($member, 'phone_mobile', ['options' => [ 'class' => 'col-md-6']])->textInput() ?>
                </div>

                <?= Html::a('Enregistrer mes données', ['/member'], ['class' => 'btn btn-success btn-fill pull-right', 'data-method' => 'post']); ?>

                <div class="clearfix"></div>

                <?php ActiveForm::end(); ?>


            </div>
        </div>
        <!-- /Profile section -->

        <!-- Address Section -->
        <div class="card">
            <div class="header">
                <h4 class="title">Adresse</h4>
            </div>
            <div class="content address-wrapper">
                <?php $form = ActiveForm::begin(); ?>

                <?= $form->field($address, 'jdls_member_id')->hiddenInput(['value'=> $member->id])->label(false); ?>

                <div class="row">
                    <?= $form->field($address, 'street', ['options' => [ 'class' => 'col-md-12']])->textInput() ?>
                </div>

                <div class="row">
                    <?= $form->field($address, 'supplement', ['options' => [ 'class' => 'col-md-12']])->textInput() ?>
                </div>

                <div class="row">
                    <?= $form->field($address, 'npa', ['options' => [ 'class' => 'col-md-6']])->textInput() ?>
                    <?= $form->field($address, 'locality', ['options' => [ 'class' => 'col-md-6']])->textInput() ?>
                </div>

                <div class="row">
                    <?= $form->field($address, 'canton', ['options' => [ 'class' => 'col-md-12']])->textInput() ?>
                </div>

                <?= Html::a('Enregistrer mon adresse', ['/member'], ['class' => 'btn btn-success btn-fill pull-right', 'data-method' => 'post']); ?>

                <div class="clearfix"></div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>
        <!-- /Address Section -->

    </div>

    <!-- Right Section
    <div class="col-md-4">
        <div class="card card-user">
            <div class="image">
                <img src="https://ununsplash.imgix.net/photo-1431578500526-4d9613015464?fit=crop&fm=jpg&h=300&q=75&w=400" alt="..."/>
            </div>
            <div class="content">
                <div class="author">
                    <a href="#">
                    <img class="avatar border-gray" src="http://fight-district.ch/wp-content/uploads/2015/10/cabal-fight-district-438x512.jpg?fit=crop&fm=jpg&h=300&q=75&w=400" alt="..."/>

                    <h4 class="title"><?= $member->first_name . ' ' . $member->last_name ?><br />
                        <small><?= Yii::$app->user->identity->username ?></small>
                    </h4>
                    </a>
                </div>
            </div>
        </div>
    </div>-->
    <!-- /Right Section -->

</div>

protected/modules/member/frontend/views/default/invoice.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;

$formatter = \Yii::$app->formatter;

$this->title = Yii::t('app', 'Fight-District | Mes Factures');

?>

<div class="row">

    <div class="col-md-12">
        <div class="card">
            <div class="header">
                <h4 class="title">Mes Factures | <span>Cours Généraux</span></h4>
            </div>
            <div class="content table-responsive table-full-width invoice-wrapper">
                <table class="table table-hover table-striped">
                    <thead>
                    	<th>Référence</th>
                    	<th>Début</th>
                    	<th>Fin</th>
                    	<th>Montant</th>
                    	<th>Statut</th>
                        <th>Actions</th>
                        <th>PDF</th>
                    </thead>
                    <tbody>
                        <?php foreach($invoices as $invoice): ?>
                        <tr>
                        	<td>
                                <?= $invoice->reference ?>
                                <?= $invoice->is_special ? ' | Cross-training' : '| Autres cours' ?>
                            </td>
                        	<td><?= $invoice->start_date == null ? '-' : Yii::$app->formatter->asDate($invoice->start_date)  ?></td>
                        	<td><?= $invoice->end_date == null ? '-' : Yii::$app->formatter->asDate($invoice->end_date)  ?></td>
                        	<td><?= $invoice->amount ?>.-</td>
                            <td><?= $invoice->statusText ?></td>
                        	<td>
                                <?php if (!$invoice->status): ?>
                                <?= Html::a('<span class="pe-7s-cash"></span>', ['payment', 'invoice_id' => $invoice->id], ['class' => 'btn btn-success btn-fill', 'data-method' => 'post']); ?>
                                <?php else: ?>
                                <span></span>
                                <?php endif ?>
                            </td>
                        	<td>
                                <?php if ($invoice->status): ?>
                                <?= Html::a('<span class="pe-7s-file"></span>', ['view-invoice', 'id' => $invoice->id], ['target' => '_blank']); ?>
                                <?php else: ?>
                                <span>-</span>
                                <?php endif ?>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
        
        <?php if($member->member_type != 1): ?>
        <?php if(!empty($invoicesSpecial)): ?>
        <div class="card">
            <div class="header">
                <h4 class="title">Mes Factures | <span>Cross-Training</span></h4>
            </div>
            <div class="content table-responsive table-full-width invoice-wrapper">
                <table class="table table-hover table-striped">
                    <thead>
                        <th>Référence</th>
                        <th>Début</th>
                        <th>Fin</th>
                        <th>Montant</th>
                        <th>Statut</th>
                        <th>Actions</th>
                        <th>PDF</th>
                    </thead>
                    <tbody>
                        <?php foreach($invoicesSpecial as $invoice): ?>
                        <tr>
                            <td>
                                <?= $invoice->reference ?>
                                <?= $invoice->is_special ? ' | Cross-training' : '| Autres cours' ?>
                            </td>
                            <td><?= $invoice->start_date == null ? '-' : Yii::$app->formatter->asDate($invoice->start_date)  ?></td>
                            <td><?= $invoice->end_date == null ? '-' : Yii::$app->formatter->asDate($invoice->end_date)  ?></td>
                            <td><?= $invoice->amount ?>.-</td>
                            <td><?= $invoice->statusText ?></td>
                            <td>
                                <?php if (!$invoice->status): ?>
                                <?= Html::a('<span class="pe-7s-cash"></span>', ['payment', 'invoice_id' => $invoice->id], ['class' => 'btn btn-success btn-fill', 'data-method' => 'post']); ?>
                                <?php else: ?>
                                <span></span>
                                <?php endif ?>
                            </td>
                            <td>
                                <?php if ($invoice->status): ?>
                                <?= Html::a('<span class="pe-7s-file"></span>', ['view-invoice', 'id' => $invoice->id], ['target' => '_blank']); ?>
                                <?php else: ?>
                                <span>-</span>
                                <?php endif ?>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
        <?php endif ?>
        <?php endif ?>

    </div>
</div>

protected/modules/member/frontend/views/default/invoice_pdf.php
<?php

use Carbon\Carbon;

$date = Carbon::now()->setTimezone('Europe/Zurich');

$this->title = Yii::t('app', 'Fight-District | PDF');

?>

<div class="container">

	<div id="pdf-view">

		<div class="company-detail">
			<h1 class="title"><?= $settings->title ?></h1>
			<div><?= $settings->street ?></div>
			<div>CH-<?= $settings->npa ?> <?= $settings->locality ?></div>
		</div>

		<br>
		<br>

		<div class="recipient-detail">
			<h1><?= $member->first_name ?> <?= $member->last_name ?></h1>
			<div><?= $member->address->street ?></div>
			<div>CH-<?= $member->address->npa ?> <?= $member->address->locality ?></div>
		</div>

		<br>
		<br>

		<div class="date">
			<div class="pull-right"><?= $settings->locality ?>, le <?= Yii::$app->formatter->asDate($date) ?></div>
		</div>

		<br>
		<br>
		<br>
		
		<div class="row">
			<h4 class="bold">Facture <?= $invoice->reference ?> </h4>
		</div>

		<br>
		<br>
		
		<?php if ($invoice->has_subscription_fee): ?>
		<div class="row">
			<div class="bold" style="float: left;">Frais d'inscription</div>
			<div class="right" style="float: right;">CHF <?= number_format($settings->subscription_cost, 2, '.', '') ?>.-</div>
		</div>
		<?php endif ?>
			
		<br>
		<div class="row">
			<div class="bold"><?= $pricing->rate->period->description ?></div> (<?= Yii::$app->formatter->asDate($invoice->start_date) ?> - <?= Yii::$app->formatter->asDate($invoice->end_date) ?>)
			<div class="right">CHF <?= number_format($pricing->rate->amount, 2, '.', '') ?>.-</div>
		</div>

		<hr>
		
		<div class="row">
			<span class="bold">Montant Payé</span>
			<span class="bold">CHF <?= number_format($invoice->amount, 2, '.', '') ?>.-</span>
		</div>

	</div>
</div>

protected/modules/member/frontend/views/default/payment.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;

use ruskid\stripe\StripeCheckout;

$formatter = \Yii::$app->formatter;

$this->title = Yii::t('app', 'Fight-District | Paiement');

if (!isset($invoice)) {
	$url = ['payment', 'id' => $pricingModel->jdls_pricing_rate_id];
} else {
	$url = ['payment', 'invoice_id' => $invoice->id];
}

?>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="content payment-wrapper">
            	<h3>Récapitulatifs des coûts</h3>
            	<h4>Type de membre: <?= $pricingModel->rate->period->pricing->category ?></h4>
				<?php if ($pricingModel->rate->is_special): ?>	
            	<h5 class="text-center">Abonnement Cross-Training</h5>
            	<?php else: ?>
				<h5 class="text-center">Abonnement général sans Cross-Training</h5>
				<?php endif; ?>

				<div class="detail">

					<?php if ($hasSubscriptionFee): ?>
	            	<div class="row">
	            		<span>Frais d'inscription</span>
	            		<span class="pull-right"><?= number_format($settings->subscription_cost, 2, '.', '') ?></span>
	            	</div>
	            	<?php endif ?>

	            	<div class="row">
	            		<span>
	            			<?php if (!isset($invoice)): ?>
	            				<span><?= $pricingModel->rate->period->description ?></span>
	            				<span class="alert alert-warning">Paiement en <?= $pricingModel->rate->frequency ?> acompte(s) de CHF <?= $pricingModel->amount ?></span>
	            			<?php else: ?>
	            				<span><?= $pricingModel->rate->period->description ?></span>
	            				<span class="alert alert-warning">Paiement pour la période du <?= $formatter->asDate($invoice->start_date) ?> au <?= $formatter->asDate($invoice->end_date) ?></span>
	            			<?php endif ?>
	            		</span>
	            		<span class="pull-right">CHF <?= number_format($pricingModel->amount, 2, '.', '') ?></span>
	            	</div>

	            	<div class="row total">
	            		<span>Montant à payer</span>
	            		<span class="pull-right">CHF <?= number_format($amount, 2, '.', '') ?></span>
	            	</div>
            	</div>
            	<div class="clearfix"></div>
            	<div class="row stripe-btn">
            		<div class="col-md-12">
	            		<?=
	            			StripeCheckout::widget([
							    'action' => Url::to($url),
							    'name' => 'Abonnement',
							    'description' => '',
							    'label' => 'Payer mon abonnement',
							    'userEmail' => Yii::$app->user->identity->email,
							    'allowRemember' => false,
							    'currency' => 'CHF',
							    'panelLabel' => 'Payer',
							    'amount' => ($amount * 100),
							    'image' => 'https://stripe.com/img/documentation/checkout/marketplace.png',
							]);
	            		?>
            		</div>
            	</div>
            </div>
        </div>
    </div>
</div>

protected/modules/member/frontend/views/default/settings.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

$formatter = \Yii::$app->formatter;

$this->title = Yii::t('app', 'Fight-District | Mes Paramètres');

?>

<div class="row">

    <div class="col-md-10">

        <?php if ($flash = Yii::$app->session->getFlash('saved-success')): ?>
            <div class="alert-tmp alert alert-success">
                <p><?=$flash?></p>
            </div>
        <?php endif;?>

        <div class="card">
            <div class="header">
                <h4 class="title">Mes Paramètres</h4>
            </div>
            <div class="content settings-wrapper">

                <?php $form = ActiveForm::begin(
                    [
                        'id' => $model->formName(),
                        'enableAjaxValidation' => true,
                        'enableClientValidation' => true,
                    ]);
                ?>

                <div class="row">
                    <?=$form->field($model, 'email', ['options' => ['class' => 'col-md-12']])->textInput(['disabled' => 'true'])?>
                </div>

                <div class="row">
                    <?=$form->field($model, 'current_password', ['options' => ['class' => 'col-md-6']])->passwordInput()?>
                    <?=$form->field($model, 'new_password', ['options' => ['class' => 'col-md-6']])->passwordInput()?>
                </div>

                <?=Html::a('Enregistrer', ['/member/settings'], ['class' => 'btn btn-success btn-fill pull-right', 'data-method' => 'post']);?>

                <div class="clearfix"></div>
                <?php ActiveForm::end();?>
            </div>
        </div>
    </div>
</div>